:hide-uri-scheme:
= debian-stratis

== What is This?
This respository is to enable the use of https://stratis-storage.github.io/[Stratis] on Debian-based GNU/Linux distros.

== Maintenance
Maintenance of this repository is best-effort.  I make no garantees of accuracy, completeness, or suitability for any purpose.

== A Note on the Sanity of Stratis
It's not.  Stratis relies on device mapper and lvm2 to create thinly provisioned volumes.  To add insult to injury, the only filesystem supported is XFS which comes with its own technical hurdles and limitations.  What does this mean to those hoping to deploy a storage solution?

1. Thinly provisioned volumes cannnot be scrubbed by device mapper or LVM which means there is no sub-filesystem garantee of consistency.
2. XFS does not store checksums of data in a way that allows it to recover corrupted data (due to kernel panic, spontaneous power off, or bit rot--among others).
3. Using XFS means your storage pools are prone to violent and catastrophic corruption of data should a kernel panic or spontaneous power off event occur without an NVDIMM or other power-off caching solution in place (which is not supported by Stratis).
4. Stratis appears to create one giant linear pool and format that as XFS, so even if the pool was thick provisioned, there'd be no checsum/FEC to use to recover damanged data by doing a scrub.

Given this, and even with the write hole problem of Btrfs, your data is still safer on a Btrfs RAID5/6 volume (as of 5.14).  That said, while performance has improved greatly, Btrfs cannot yet achieve the IOPs of XFS.

If you have NVDIMMS or some really fast, high wear (DAS) NVMe drives, ZFS may be a better option, though you must also understand that ZFS is not a cure all.  The era if its development and the inability of its developers to see a purely solid-state future is starting to show.  IF you aren't using NVDIMMS or REALLY fast (enterprise SLC/MLC) NVMe's (most home deployments), an L2ARC is marginally helpful and an SLOG is utterly pointless.  Such situations negate the benefits of the complexity of a ZFS setup...which brings us back to Btrfs (and making sure you have stable hardware).  At this point RAID5/6 on Btrfs is fine as long as metadata is RAID1/RAID1c3, respectively, with some caveats.

More information on Btrfs RAID5/6 here: https://btrfs.readthedocs.io/en/latest/btrfs-man5.html#raid56-status-and-recommended-practices

== A Note About the Current State of Storage
At the time of writing all modern file systems in public use (APFS, Btrfs, ReFS, ZFS, Stratis, LVM2 + ?) are slightly better than awful. The fact we even made it this far is amazing. The reality is that storage is hard. Safe, performant storage is a gargantuan effort, and one of the most difficult problems for humanity to solve.

== Installation

1. Install https://www.rust-lang.org/[Rust]
2. Clone this repository, and run dependencies_debian.sh
3. Install stratisd by following the build instructions at https://github.com/stratis-storage/stratisd[the stratisd repo]
4. Install external python requirements ```python3 -m pip install justbytes```
5. Install stratis-cli using the instructions at the https://github.com/stratis-storage/stratis-cli[official repo]

NOTE: Debian is not supported by stratis.  What follows below is a work in progress as I figure it out.  Contributions welcome.

There are some issues left to be resolved.  The script to install dependencies and resolve build issues is a work in progress.  The "script" currently provided lacks flow control, error check, dependency resolution and install validation.  It is little more than a list of commands you might type in your terminal if trying to do this yourself, and you were in a hurry for a proof-of-concept.

1. Currently even with ```make build-all``` and ```make install``` the binaries, udev rules, dbus polcies, and systemd services are not installed.  This is likely something I am doing wrong, or an errant personal expection not being met.  But I'm getting close!
