:hide-uri-scheme:
= debian-stratis

== What is This?
This respository is to enable the use of https://stratis-storage.github.io/[Stratis] on Debian-based GNU/Linux distros.

== Maintenance
Maintenance of this repository is best-effort.  I make no garantees of accuracy, completeness, or suitability for any purpose.

== A Note on the Sanity of Stratis
It's not.  Stratis relies on device mapper and lvm2 to create thinly provisioned volumes.  To add insult to injury, the only filesystem supported is XFS which comes with its own technical hurdles and limitations.  What does this mean to those hoping to deploy a storage solution?

1. Thinly provisioned volumes cannnot be scrubbed by device mapper or LVM which means there is no sub-filesystem garantee of consistency.
2. XFS does not store checksums of data in a way that allows it to recover corrupted data (due to kernel panic, spontaneous power off, or bit rot--among others).
3. Using XFS means your storage pools are prone to violent and catastrophic corruption of data should a kernel panic or spontaneous power off event occur without an NVDIMM or other power-off caching solution in place (which is not supported by Stratis).

Given this, and even with the write hole problem of Btrfs, your data is still safer on a Btrfs RAID5/6 volume (as of 5.14).  That said, while performance has improved greatly, Btrfs cannot yet achieve the IOPs of XFS.

If you have NVDIMMS or some really fast, high wear (DAS) NVMe drives, ZFS may be a better option, though you must also understand that ZFS is not a cure all.  The era if its development and the inability of its developers to see a purely solid-state future is starting to show.  IF you aren't using NVDIMMS or REALLY fast (enterprise SLC/MLC) NVMe's (most home deployments), an L2ARC is marginally helpful and an SLOG is utterly pointless.  Such situations negate the benefits of the complexity of a ZFS setup...which brings us back to Btrfs (and making sure you have stable hardware).  At this point RAID5/6 on Btrfs is fine as long as metadata is RAID1/RAID1c3, respectively, with some caveats.

More information on Btrfs RAID5/6 here: https://btrfs.readthedocs.io/en/latest/btrfs-man5.html#raid56-status-and-recommended-practices

== A Note About the Current State of Storage
At the time of writing all modern file systems in public use (APFS, Btrfs, ReFS, ZFS, Stratis, LVM2 + ?) are slightly better than awful. The fact we even made it this far is amazing. The reality is that storage is hard. Safe, performant storage is a gargantuan effort, and one of the most difficult problems for humanity to solve.

== Installation

1. Install https://www.rust-lang.org/[Rust]
2. Clone this repository, and run dependencies_debian.sh
3. Install stratisd by following the build instructions at https://github.com/stratis-storage/stratisd[the stratisd repo]
4. Install external python requirements ```python3 -m pip install justbytes```
5. Install stratis-cli using the instructions at the https://github.com/stratis-storage/stratis-cli[official repo]

NOTE: Debian is not supported by stratis.  What follows below is a work in progress as I figure it out.  Contributions welcome.

There are some issues left to be resolved.  I'll write a script to take care of them as get a chance.

1. Cloning the stratisd repo and runing ```make``` succeeds, but ```sudo make install``` fails because docs are made in a separate step.
2. When stratisd is built it appears to go to the default cargo install dir ($HOME/.cargo/bin) and the Makefile does not accomodate that.
3. The systemd services need to be installed.  (```make install``` might do this later if docs succeed, haven't checked)
4. stratisd fails to start because it cannot find ```thin_check``` which is provided by thin-provisioning-tools
5. With ```thin_check``` present, stratisd complains as follows:

[quote, stratisd]
The IPC thread exited with an error: Dbus error: Connection "1.25" is not allowed to own the service "org.storage.stratis3" due to security policies in the configuration file; shutting down stratisd...
