:hide-uri-scheme:
= debian-stratis

== What is This?
This respository is to enable the use of https://stratis-storage.github.io/[Stratis] on Debian-based GNU/Linux distros.

== Maintenance
Maintenance of this repository is best-effort.  I make no garantees of accuracy, completeness, or suitability for any purpose.

== A Note on the Sanity of Stratis
I've spent a lot of time (years now) with a misconception of what Stratis is and aims to achieve.  Stratis might be for you if all of the following are true:

1. You need the scalability of ZFS
2. You need the performance capability of ZFS, but you don't quite need the IOPs of Lustre and certainly don't want or need that kind of infrastructre
3. You need the flexibility of Btrfs
4. You have a sound disaster recovery strategy that includes backups with long-term storage not on Stratis
5. You aren't willing to wait for Btrfs developers to resolve the write hole problem
6. Bit rot may be a concern but it is not a high priority because of #4 or because data simply isn't stored long term on your Stratis pool

== A Note About the Current State of Storage
At the time of writing all modern file systems in public use (APFS, Btrfs, ReFS, ZFS, Stratis, LVM2 + ?) are slightly better than awful. The fact we even made it this far is amazing. The reality is that storage is hard. Safe, performant storage is a gargantuan effort, and one of the most difficult problems for humanity to solve.  Do not trust that your primary storage solution will always be trustworthy.  Over a long enough time span, the probability of failure is 100%.

== Installation

1. Clone this repository, and run dependencies_debian.sh

At this stage, you'll need to troubleshoot what isn't working.

NOTE: Debian is not supported by stratis.  What follows below is a work in progress as I figure it out.  Contributions welcome.

There are some issues left to be resolved.  The script to install dependencies and resolve build issues is a work in progress.  The "script" currently provided lacks flow control, error check, dependency resolution and install validation.  It is little more than a list of commands you might type in your terminal if trying to do this yourself, and you were in a hurry for a proof-of-concept.

1. Currently even with ```make build-all``` and ```make install``` the binaries, udev rules, dbus polcies, and systemd services are not installed.  This is likely something I am doing wrong, or an errant personal expection not being met.  But I'm getting close!
